### ISSUE TITLE
PyPI version bump?

### ISSUE THREAD

**Issue by yuzeh** [BerkeleyAutomation/meshrender#9]
The version that's in PyPI has a serious memory leak when you  render multiple times in one script.

This problem is fixed in master, though.

**Comment by mmatl** [comment]
Sorry, will push a new version out soon. Also, there's a much better repo available on PyPi now called pyrender: https://github.com/mmatl/pyrender. I'd suggest moving over to that, as I'm not going to continue developing for this repo.

**Comment by yuzeh** [comment]
Okay, thanks.
